package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"

	"golang.org/x/tools/go/packages"
)

// generate produces a file with a DexKey method for each named struct type.
// DexKey is an injective canonical encoding: every primitive token either has
// a fixed width or is terminated or length prefixed, and slices are length
// prefixed, so distinct values never share an encoding.
func generate(dir string, typeNames []string) ([]byte, error) {
	cfg := &packages.Config{Mode: packages.NeedName | packages.NeedTypes, Dir: dir}
	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		return nil, err
	}
	if len(pkgs) != 1 {
		return nil, fmt.Errorf("dexgen: expected one package, got %d", len(pkgs))
	}
	pkg := pkgs[0]
	if len(pkg.Errors) > 0 {
		return nil, fmt.Errorf("dexgen: %v", pkg.Errors[0])
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by dexgen. DO NOT EDIT.\n\npackage %s\n\nimport \"strconv\"\n\n", pkg.Name)
	b.WriteString(helpers)

	for _, name := range typeNames {
		obj := pkg.Types.Scope().Lookup(name)
		if obj == nil {
			return nil, fmt.Errorf("dexgen: type %s not found in %s", name, pkg.PkgPath)
		}
		fmt.Fprintf(&b, "// DexKey is an injective canonical encoding of the value, usable as a\n")
		fmt.Fprintf(&b, "// dex.RunKeyed key.\n")
		fmt.Fprintf(&b, "func (v %s) DexKey() string {\n", name)
		fmt.Fprintf(&b, "var b []byte\n")
		if err := emitValue(&b, "v", obj.Type(), 0); err != nil {
			return nil, fmt.Errorf("dexgen: %s: %w", name, err)
		}
		fmt.Fprintf(&b, "return string(b)\n}\n\n")
	}

	return format.Source(b.Bytes())
}

func emitValue(b *bytes.Buffer, expr string, t types.Type, depth int) error {
	switch u := t.Underlying().(type) {
	case *types.Basic:
		switch {
		case u.Info()&types.IsBoolean != 0:
			fmt.Fprintf(b, "b = dexgenBool(b, bool(%s))\n", expr)
		case u.Info()&types.IsUnsigned != 0:
			fmt.Fprintf(b, "b = dexgenUint(b, uint64(%s))\n", expr)
		case u.Info()&types.IsInteger != 0:
			fmt.Fprintf(b, "b = dexgenInt(b, int64(%s))\n", expr)
		case u.Info()&types.IsFloat != 0:
			fmt.Fprintf(b, "b = dexgenFloat(b, float64(%s))\n", expr)
		case u.Info()&types.IsString != 0:
			fmt.Fprintf(b, "b = dexgenString(b, string(%s))\n", expr)
		default:
			return fmt.Errorf("unsupported basic type %s in %s", u, expr)
		}
	case *types.Struct:
		for i := 0; i < u.NumFields(); i++ {
			f := u.Field(i)
			if err := emitValue(b, expr+"."+f.Name(), f.Type(), depth); err != nil {
				return err
			}
		}
	case *types.Slice:
		v := fmt.Sprintf("e%d", depth)
		fmt.Fprintf(b, "b = dexgenInt(b, int64(len(%s)))\n", expr)
		fmt.Fprintf(b, "for _, %s := range %s {\n", v, expr)
		if err := emitValue(b, v, u.Elem(), depth+1); err != nil {
			return err
		}
		fmt.Fprintf(b, "}\n")
	case *types.Array:
		v := fmt.Sprintf("e%d", depth)
		fmt.Fprintf(b, "for _, %s := range %s {\n", v, expr)
		if err := emitValue(b, v, u.Elem(), depth+1); err != nil {
			return err
		}
		fmt.Fprintf(b, "}\n")
	default:
		return fmt.Errorf("unsupported type %s (%T) in %s", t, u, expr)
	}
	return nil
}

const helpers = `func dexgenBool(b []byte, v bool) []byte {
	if v {
		return append(b, 't')
	}
	return append(b, 'f')
}

func dexgenInt(b []byte, v int64) []byte {
	b = strconv.AppendInt(b, v, 10)
	return append(b, ',')
}

func dexgenUint(b []byte, v uint64) []byte {
	b = strconv.AppendUint(b, v, 10)
	return append(b, ',')
}

func dexgenFloat(b []byte, v float64) []byte {
	b = strconv.AppendFloat(b, v, 'b', -1, 64)
	return append(b, ',')
}

func dexgenString(b []byte, v string) []byte {
	b = strconv.AppendInt(b, int64(len(v)), 10)
	b = append(b, ':')
	return append(b, v...)
}

`
