// Code generated by dexgen. DO NOT EDIT.

package fixture

import "strconv"

func dexgenBool(b []byte, v bool) []byte {
	if v {
		return append(b, 't')
	}
	return append(b, 'f')
}

func dexgenInt(b []byte, v int64) []byte {
	b = strconv.AppendInt(b, v, 10)
	return append(b, ',')
}

func dexgenUint(b []byte, v uint64) []byte {
	b = strconv.AppendUint(b, v, 10)
	return append(b, ',')
}

func dexgenFloat(b []byte, v float64) []byte {
	b = strconv.AppendFloat(b, v, 'b', -1, 64)
	return append(b, ',')
}

func dexgenString(b []byte, v string) []byte {
	b = strconv.AppendInt(b, int64(len(v)), 10)
	b = append(b, ':')
	return append(b, v...)
}

// DexKey is an injective canonical encoding of the value, usable as a
// dex.RunKeyed key.
func (v State) DexKey() string {
	var b []byte
	b = dexgenInt(b, int64(v.Round))
	b = dexgenBool(b, bool(v.Done))
	b = dexgenInt(b, int64(len(v.Names)))
	for _, e0 := range v.Names {
		b = dexgenString(b, string(e0))
	}
	b = dexgenInt(b, int64(len(v.Log)))
	for _, e0 := range v.Log {
		b = dexgenString(b, string(e0.Kind))
		b = dexgenInt(b, int64(e0.N))
	}
	for _, e0 := range v.Flags {
		b = dexgenBool(b, bool(e0))
	}
	return string(b)
}
