// Code generated by dexgen. DO NOT EDIT.

package fixture

import "strconv"

// DexKey is an injective canonical encoding of the value, usable as a
// dex.RunKeyed key.
func (v Entry) DexKey() string {
	var b []byte
	b = strconv.AppendInt(b, int64(len(v.Kind)), 10)
	b = append(b, ':')
	b = append(b, v.Kind...)
	b = strconv.AppendInt(b, int64(v.N), 10)
	b = append(b, ',')
	return string(b)
}
