// Code generated by dexgen. DO NOT EDIT.

package fixture

import "strconv"

// DexKey is an injective canonical encoding of the value, usable as a
// dex.RunKeyed key.
func (v State) DexKey() string {
	var b []byte
	b = strconv.AppendInt(b, int64(v.Round), 10)
	b = append(b, ',')
	if v.Done {
		b = append(b, 't')
	} else {
		b = append(b, 'f')
	}
	b = strconv.AppendInt(b, int64(len(v.Names)), 10)
	b = append(b, ';')
	for _, e0 := range v.Names {
		b = strconv.AppendInt(b, int64(len(e0)), 10)
		b = append(b, ':')
		b = append(b, e0...)
	}
	b = strconv.AppendInt(b, int64(len(v.Log)), 10)
	b = append(b, ';')
	for _, e0 := range v.Log {
		b = strconv.AppendInt(b, int64(len(e0.Kind)), 10)
		b = append(b, ':')
		b = append(b, e0.Kind...)
		b = strconv.AppendInt(b, int64(e0.N), 10)
		b = append(b, ',')
	}
	for _, e0 := range v.Flags {
		if e0 {
			b = append(b, 't')
		} else {
			b = append(b, 'f')
		}
	}
	return string(b)
}
